### ISSUE TITLE
Error while installing 'Azure Tools' extension

### ISSUE THREAD

**Issue by macubexx** [microsoft/vsmarketplace#781] opened 2023-10-07 00:46 UTC
Type: <b>Bug</b>

I tried installing Azure Tools but it always have an error message that says "Error while installing 'Azure Tools' extension. Please check the log for more details. Try Downloading Manually..." I tried manually installing the other Azure apps and they got installed except for Azure Storage. The log for this is 

2023-10-07 08:25:24.440 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-dotnettools.dotnet-interactive-vscode' wants API proposal 'languageConfigurationAutoClosingPairs' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-10-07 08:25:24.461 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot-chat' wants API proposal 'terminalContextMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-10-07 08:25:28.444 [info] [perf] Render performance baseline is 92ms
2023-10-07 08:25:48.006 [error] CorruptZip: end of central directory record signature not found
    at w.download (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:141)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async W.x (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:19882)
    at async W.h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:17926)
2023-10-07 08:25:48.064 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at w.download (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:141)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async W.x (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:19882)
    at async W.h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:17926)
2023-10-07 08:30:09.257 [error] CorruptZip: end of central directory record signature not found
    at w.download (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:141)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async W.x (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:19882)
    at async W.h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:17926)
2023-10-07 08:30:09.289 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at w.download (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:141)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async W.x (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:19882)
    at async W.h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:17926)

Also at the manual download site of the app here is the message:
{
    "$id": "1",
    "innerException": null,
    "message": "Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).",
    "typeName": "Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server",
    "typeKey": "RequestBlockedException",
    "errorCode": 0,
    "eventId": 3000
}

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by madhurivadaligithub** [comment] 2023-10-13 11:43
Hi @macubexx 
Thank you for reaching VS Marketplace Support Team. We are following up to determine how best to address it.

 -VS Marketplace Team

**Comment by lyndaidaii** [comment] 2023-10-13 17:56
@macubexx, could you create issue here: https://github.com/microsoft/vscode-node-azure-pack/issues

**Comment by madhurivadaligithub** [comment] 2023-10-24 05:13
Hi @macubexx  Since   We are closing the issue as we have not heard from you in a while.

If the issue is still there, please feel free to comment or start a new issue.

Thanks,
VS Marketplace Team

**Closed by madhurivadaligithub** 2023-10-24 05:13 UTC
