### ISSUE TITLE
report

### ISSUE THREAD

**Issue by harunsalman02** [microsoft/vsmarketplace#531] opened 2022-12-09 04:27 UTC
Type: <b>Bug</b>

there isn't any extension

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.16299
Modes:
Sandboxed: No

**Comment by kj0171** [comment] 2022-12-12 06:36
Can you please elaborate more about the issue?  If possible, please try tagging screenshots along with the issue.
Thanks.

**Comment by JatinSanghvi** [comment] 2023-02-04 05:58
This seems to be same as #533 which was created at around the same time. The extensions did not load as the requests to Gallery CDN were failing. This turned out to be a temporary issue. The users who original reported it are no longer seeing it. I will close this one.

@harunsalman02, if you are still facing this issue, please follow the steps as I mentioned in https://github.com/microsoft/vsmarketplace/issues/540#issuecomment-1411490797 and we will reconsider. It would also be helpful if you can add a comment below stating whether the issue is fixed or still persists.

**Closed by JatinSanghvi** 2023-02-04 05:58 UTC
