### ISSUE TITLE
after installing extension still showing please install extension 

### ISSUE THREAD

**Issue by Shivammudgal2000** [microsoft/vsmarketplace#210] opened 2021-10-17 06:33 UTC
Issue Type: <b>Bug</b>

i install askia QeXML  generator and Batch Rename extension and when i try to run the program vs code still showing there is no extension for 'plain text' extension 

VS Code version: Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:19:42.089Z)
OS version: Windows_NT x64 10.0.22471
Restricted Mode: No

**Comment by Neelima10735584** [comment] 2024-10-29 11:46
Hi,

Thanks for reaching VS Marketplace Team, we are able to see mentioned extension in Marketplace. hence closing the issue. If the issue is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team

**Closed by Neelima10735584** 2024-10-29 11:46 UTC
