### ISSUE TITLE
Fix the copy button on vscode marketplace website

### ISSUE THREAD

**Issue by willster277** [microsoft/vsmarketplace#410] opened 2022-06-04 20:34 UTC
**Not the VSCode app itself; issue occurs on marketplace.visualstudio.com**

---

Every single time, without fail, that I have viewed an extension on this site, (assuming I want the extension) I have clicked the "copy" button and ended up pasting nonsense into my VSCode quick open.

![Screenshot from 2022-06-04 21-18-24](https://user-images.githubusercontent.com/85991558/172024346-58fd7eef-87fc-40da-b4a0-2de2841d9fb0.png)

The button does not work. Everything about it visually indicates it should copy the extension command to my clipboard, and the markup makes this even more certain;
```html
<button 
  class="copy-to-clipboard-button" 
  id="copy-to-clipboard-button" 
  title="Copy to clipboard"
  >
    Copy
</button>
```

However it simply does not work.

I have accepted all cookies, and on Chrome I have no settings changed from default which could be effecting this, on FireFox I have, but given the Chrome default behaviour I don't believe my settings on FireFox are the cause of this problem.

On page load there is this output;
```
Content Security Policy: Ignoring "'unsafe-inline'" within script-src or style-src: nonce-source or hash-source specified

This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.

Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").     moz-extension:136:52

Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").     sandbox eval code:9:350

Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").     moz-extension:2091:49

[CustomCSS Injector] Applied custom CSS.
```

There's a change that it's just this cookie-related script, though if this is the case then there's no info here on why the copy button isn't functioning correctly;

```html
<script nonce="" src="/_static/tfs/M204_20220530.3/_scripts/TFS/min/Gallery/Client/Common/ManageCookieDrop.js"></script>
```

Looking at every other `script-src` on the page, it looks like all of them are just components, the one above is the only one i saw with a `nonce` field.

---

Browsers effected:  
- FireFox 100 (100.0.2)
- Chrome 101 (101.0.4951.54)
- possibly others (untested)
OS: Linux (Pop!_OS 21.10)

If this isn't your ball park, please let the frontend team for the marketplace know, I'm tired of pasting code snippets from an hour ago into my quick open when I try to install an extension

**Comment by isidorn** [comment] 2022-06-06 10:37
@willster277 thanks for opening this issue, moving it to the VS Marketplace repo.

@prashantvc can you please help here

**Comment by prashantvc** [comment] 2022-06-07 07:14
@willster277 Thanks a a lot for the bug report! Unfortunately we do not support `copy` in the VS Marketplace.
Could you share what extension is this? 

The installation instructions you see shouldn't exist.

**Closed by prashantvc** 2022-06-07 07:14 UTC

**Comment by willster277** [comment] 2022-06-07 10:57
@prashantvc the installation instructions in the image in the original post are there exactly as shown on ever VSCode extension, both for me and for all the footage I've seen of the site (on YouTube for example).

I'm not sure what you mean when you say it shouldn't be there/is not supported.

**Comment by qazhub** [comment] 2022-10-13 04:01
I don't understand. @prashantvc The author attached a screenshot directly taken from the VS marketplace, it's an installation instruction for **ALL** VSCode extensions, why would you say it's not supported?

Well, if you are willing to check for yourself, here's a step by step guide to reproduce this issue:

- Go to the VS marketplace, select VSCode category. Or you can directly visit this page: https://marketplace.visualstudio.com/vscode
  ![image](https://user-images.githubusercontent.com/76024777/195496062-9cdd8f95-ac01-456c-abe2-03c22e1947c5.png)
- Select any one of the extension. For example you can click on [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python), which is one of the official extensions from Microsoft.  
  ![image](https://user-images.githubusercontent.com/76024777/195496106-ee99af28-8b23-4529-834d-e4f096600e77.png)
- Now, here's the "copy" button, together with the installation instruction:
  ![image](https://user-images.githubusercontent.com/76024777/195496176-b91cc9ec-25b9-49af-a23f-368c56f76087.png)

Why would you say it's not supported if it's been there since the beginning?

**Comment by qazhub** [comment] 2022-10-13 04:38
As far as I can tell, this is a duplicate of #366. I think it's valid, either the copy feature need to be fixed, or the copy button should be removed completely.

**Comment by isidorn** [comment] 2022-10-13 08:09
I agree with the above ☝️
