### ISSUE TITLE
extension issue

### ISSUE THREAD

**Issue by MURTAZAJAN1122** [microsoft/vsmarketplace#485] opened 2022-09-26 16:39 UTC
Type: <b>Bug</b>

hi sir , 
i hope everyone will be fine my problem is that the extension of python is not installing in my vs studio please solve my problem.
thanks

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 6.3.9600
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment] 2022-09-27 07:38
@MURTAZAJAN1122 Can you please share more details about this issue (any error messages)

**Comment by madhurivadaligithub** [comment] 2022-10-06 13:13
Hi @MURTAZAJAN1122  Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.

**Comment by MURTAZAJAN1122** [comment] 2022-10-06 13:21
Error in Installation of python extension

**Comment by SaiKanth007** [comment] 2022-10-06 13:21
Can you share more details about the error you are getting?
A screenshot of the error or recording of your issue would help us better understand the issue.

**Comment by MURTAZAJAN1122** [comment] 2022-10-06 13:33
I an already shared.

**Comment by MURTAZAJAN1122** [comment] 2022-10-07 14:38
No response.

**Comment by isidorn** [comment] 2022-10-07 16:44
Closing until issue has reproducable steps.

**Closed by isidorn** 2022-10-07 16:44 UTC
Labels: need-information
