### ISSUE TITLE
cannot install extension

### ISSUE THREAD

**Issue by Bo-Yaser** [microsoft/vsmarketplace#980] opened 2024-08-10 03:49 UTC
Type: <b>Bug</b>

cannot install any extension

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by Bo-Yaser** [comment] 2024-08-10 03:57
![Desktop Screenshot 2024 08 10 - 06 52 36 70](https://github.com/user-attachments/assets/7b54ad3d-52a8-402c-8ba8-025096b8eca2)

**Comment by Bo-Yaser** [comment] 2024-08-10 03:58
and i cant download it manualy too

**Comment by Neelima10735584** [comment] 2024-08-12 12:29
Hi @Bo-Yaser,

Thank you for reaching out to the VS Marketplace Team. We were unable to reproduce the issue. Could you please share more details and any logs about the issue to investigate further.

Thanks,
VS Marketplace Support Team

**Comment by madhurivadaligithub** [comment] 2024-08-21 10:21
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue,

**Closed by madhurivadaligithub** 2024-08-21 10:21 UTC
Labels: needs-info
