### ISSUE TITLE
failed to download extensions

### ISSUE THREAD

**Issue by luai99** [microsoft/vsmarketplace#220] opened 2021-10-26 12:16 UTC
Issue Type: <b>Bug</b>

how can i solve that when i try to download a new extenasion vs cod say that you have error proxy connection failed or error while fetching extensions xhr failed
please help me

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 6.3.9600
Restricted Mode: No

**Comment by tomthecarrot** [comment] 2021-11-03 21:03
This seems to be a duplicate of #214.

**Comment by Neelima10735584** [comment] 2024-10-24 10:04
Hi,
 
Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, it will help us to investigate, if you can share the network log (command: Developer: Open Logs Folder).
 
Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment] 2024-10-29 11:04
Closing the issue since there has been no updates on the information requested.

Thanks,
VS Marketplace Team

**Closed by Neelima10735584** 2024-10-29 11:04 UTC
Labels: needs-info
