### ISSUE TITLE
Live Server not working properly

### ISSUE THREAD

**Issue by PabloAli05** [microsoft/vsmarketplace#1088] opened 2024-12-11 09:50 UTC
Type: <b>Performance Issue</b>

When i open the server, the page opens up but when i edit or change the coding or contents the changes doesnt apply when i refresh the page. It only applies when i close the server and reopen the live server. How do i fix this as it is frustrating to keep on closing and opening the live server.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by Neelima10735584** [comment] 2024-12-12 11:43
Hi,

Thanks for reaching VS Marketplace Support Team, could you please share detailed steps to reproduce the issue, details of the publisher and Extension details to investigate further.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment] 2024-12-19 10:37
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team

**Closed by Neelima10735584** 2024-12-19 10:37 UTC
Labels: needs-info, Customer Support
