### ISSUE TITLE
Provide details for when your extension has suspicious content 

### ISSUE THREAD

**Issue by estruyf** [microsoft/vsmarketplace#344] opened 2022-03-09 09:56 UTC
I wanted to publish a new version of my extension, and I got the following message:

```
Your extension has suspicious content. Please fix your extension metadata, or reach contact support if you need assistance.
```

There hasn't been a change to the extension metadata since the last release. Not sure why it is happening. Also, it would be great to point out the actual issue.

**Comment by estruyf** [comment] 2022-03-09 11:23
Just verified the documentation again and did a couple of tests, the same happens on the **Manage Publishers & Extensions** page.

![Screenshot 2022-03-09 at 12 18 42](https://user-images.githubusercontent.com/2900833/157431643-3e059e0a-99ec-49a3-9c84-841752f4f318.png)

At least, there is a pointer to the docs which point out that the following constraints are checked:

- The icon provided in package.json may not be an SVG.
- The badges provided in the package.json may not be SVGs unless they are from [trusted badge providers](https://code.visualstudio.com/api/references/extension-manifest#approved-badges).
- Image URLs in README.md and CHANGELOG.md need to resolve to https URLs.
- Images in README.md and CHANGELOG.md may not be SVGs unless they are from [trusted badge providers](https://code.visualstudio.com/api/references/extension-manifest#approved-badges).

I validated this myself, and all should be valid. Just to make sure I did the following:

- Cleared out the readme and only kept the title in it.
- Verified that no images are used in the changelog
- Removed badges

Packaged and uploaded the `vsix` file again, but still, validation fails.

**Comment by prashantvc** [comment] 2022-03-09 11:23
@estruyf I apologies you have to experience this.
Could you share your extension details? We will take a look

**Comment by estruyf** [comment] 2022-03-09 11:27
Here is my compressed vsix file. Hope this helps.

[vscode-front-matter-beta-7.0.1956421.vsix.zip](https://github.com/microsoft/vsmarketplace/files/8214226/vscode-front-matter-beta-7.0.1956421.vsix.zip)

**Comment by prashantvc** [comment] 2022-03-09 11:29
Appreciate your patience while we investigate the issue. 
I will see if we can provide you a workaround in the meantime

**Comment by tronical** [comment] 2022-03-09 12:18
We're running into the same error message when trying to update [our extension](https://marketplace.visualstudio.com/items?itemName=Slint.slint-nightly). Do you know what could cause this error message?

**Comment by gareth-rees** [comment] 2022-03-09 15:49
I encountered the same problem trying to update the [Time Travel Debug for C/C++ extension](https://marketplace.visualstudio.com/items?itemName=Undo.udb). Here's a screenshot of the error message:

![Screenshot from 2022-03-09 09-33-01](https://user-images.githubusercontent.com/922721/157476938-f72ad0d0-092a-4e9d-8e3d-aa72e659b61b.png)

I was unable to contact marketplace support due to issue #347. I've attached the offending .vsix in case that will help diagnose the problem: [udb-1.2.0.vsix.zip](https://github.com/microsoft/vsmarketplace/files/8216071/udb-1.2.0.vsix.zip)

**Comment by prashantvc** [comment] 2022-03-09 17:45
We have noticed surge of spam extensions in the marketplace this week. We dialed up the spam detection code, and this is side effect, unfortunately.

Please note that the team is working tirelessly to restore the service, and we apricate your patience

**Comment by sathaker** [comment] 2022-03-09 18:32
Hi @estruyf @tronical @gareth-rees 

We have shipped the fix and you should be able to update your extension as desired. Feel free to retry and confirm here. Thank you for your patience.

**Comment by estruyf** [comment] 2022-03-09 19:18
Thanks @sathaker, I can confirm that the APIs are working again.

**Comment by gareth-rees** [comment] 2022-03-09 20:13
@sathaker @prashantvc I was able to update the [Time Travel Debug for C/C++ extension](https://marketplace.visualstudio.com/manage/publishers/Undo). Thank you for fixing the problem.

**Comment by dimacodota** [comment] 2022-03-10 10:09
We're running into the same issue,  when trying to update the [Tabnine extension](https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode)

**Comment by Vaporizer-dev** [comment] 2022-03-11 14:54
Hi @prashantvc 
I'm having the same issue, unable to upload vscode theme like before.(extension has suspicious content...)

**Comment by Lakshmikanth2001** [comment] 2022-03-18 04:07
Even I am facing the same error

`Your extension has suspicious content. Please fix your extension metadata, or reach contact support if you need assistance.`

[githooks-0.1.3.zip](https://github.com/microsoft/vsmarketplace/files/8301461/githooks-0.1.3.zip)

please help me out

**Comment by anupkmr03** [comment] 2022-11-02 10:55
@Lakshmikanth2001 As @prashantvc mentioned we enabled the spam detection code, and this is side effect. If you are still facing the problem, please let us know we will investigate further.

**Comment by Lakshmikanth2001** [comment] 2022-11-02 10:57
no the issue is resolved thank you

**Comment by anupkmr03** [comment] 2022-11-02 11:00
Thanks @Lakshmikanth2001  for the update closing the issue.

**Closed by anupkmr03** 2022-11-02 11:00 UTC
Labels: bug
