### ISSUE TITLE
why my extensions atre not downloading on vs code

### ISSUE THREAD

**Issue by SmiSow** [microsoft/vsmarketplace#914] opened 2024-05-25 09:28 UTC
Type: <b>Bug</b>

entensions are not installing good network but also extensions are not downloading 

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by SmiSow** [comment] 2024-05-25 09:29
![Screenshot 2024-05-25 150128](https://github.com/microsoft/vsmarketplace/assets/170798183/75f420e1-ac24-49e0-9943-4cdfa0dc1ae3)

**Comment by madhurivadaligithub** [comment] 2024-05-28 06:55
Hi @SmiSow ,

Thank you for reaching out to the VS Marketplace Team. We are unable to reproduce the issue. Are you still facing difficulties installing this Python extension?

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment] 2024-06-05 04:37
Since we have not received the required information, we are closing the issue. Please feel free to reopen or create a new issue if the problem still persists.

Regards,
VS Marketplace Team

**Closed by madhurivadaligithub** 2024-06-05 04:37 UTC
Labels: needs-info
