### ISSUE TITLE
Window10 the cpu is 100% after updated to version 1.63.1

### ISSUE THREAD

**Issue by ghfkui** [microsoft/vsmarketplace#278] opened 2021-12-15 05:55 UTC
Issue Type: <b>Performance Issue</b>

When opened the vscode, the cpu is used 100% in window 10 after updated to version 1.6.3.1. The detail of version is as follow:
Version: 1.63.1 (user setup)
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:54.292Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19041

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by ghfkui** [comment] 2021-12-15 05:57
![image](https://user-images.githubusercontent.com/4645418/146131430-74c54b05-287e-4ea9-ac8a-f188dc87aa8c.png)
Used extensions is in image

**Comment by isidorn** [comment] 2022-01-03 09:37
@ghfkui please use F1 > extension bisect to figure out what extension is causing this and then file the issue against that extension.
If you believe it is not an extension issue then please file this against the vscode repository.

For now closing this since the issue is not on the Marketplace side

**Closed by isidorn** 2022-01-03 09:37 UTC
