### ISSUE TITLE
Cannot update/install extensions

### ISSUE THREAD

**Issue by geoffdudds** [microsoft/vsmarketplace#582] opened 2023-02-10 17:50 UTC
Type: <b>Bug</b>

I cannot update or install extensions from the marketplace side panel.
I am able to install / update most extensions manually. The exception is Python (ms-python.python), which seems to have been removed and cannot be installed.

The issue does not go away if I run vscode with extensions disabled.
I have also tried downloading and installing vscode over my current installation.

It is difficult to say how to reproduce since I cannot resolve the issue.
I first noticed the issue when I was experimenting with dev containers, which involved installing docker, wsl, and dev container extensions, all of which I've temporarily uninstalled.

This is the log from when I start vscode with extensions disabled in an empty project and click `Install` on the _Python_ extension.

```
2023-02-10 09:30:57.986 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'commentsResolvedState' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-02-10 09:30:58.687 [warning] [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
2023-02-10 09:31:01.138 [info] [perf] Render performance baseline is 172ms
2023-02-10 09:31:09.360 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'commentsResolvedState' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-02-10 09:31:13.470 [info] [perf] Render performance baseline is 158ms
2023-02-10 09:31:29.994 [error] UnhandledException: Signature: UnhandledException
    at yt.download (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:62:17985)
    at async $.h (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171351)
2023-02-10 09:31:32.688 [error] UnhandledException,UnhandledException,UnhandledException: Error: UnhandledException,UnhandledException,UnhandledException
    at vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:89578
    at Array.reduce (<anonymous>)
    at E (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:89564)
    at ne.D (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:80916)
    at async ne.z (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:78417)
    at async ne.installFromGallery (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:74855)
2023-02-10 09:36:43.116 [error] Error: UnhandledException,UnhandledException,UnhandledException
    at vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:89578
    at Array.reduce (<anonymous>)
    at E (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:89564)
    at ne.D (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:80916)
    at async ne.z (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:78417)
    at async ne.installFromGallery (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:74855)
2023-02-10 09:36:43.149 [error] UnhandledException,UnhandledException,UnhandledException: Error: UnhandledException,UnhandledException,UnhandledException
    at vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:89578
    at Array.reduce (<anonymous>)
    at E (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:89564)
    at ne.D (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:80916)
    at async ne.z (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:78417)
    at async ne.installFromGallery (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:74855)
```

This is the log if I then select `Update` on the _GitHub Pull Request and Issues_ extension:
```
2023-02-10 09:40:13.250 [error] Signature: UnhandledException
    at yt.download (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:62:17985)
    at async $.h (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171351)
2023-02-10 09:40:13.274 [error] UnhandledException: Signature: UnhandledException
    at yt.download (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:62:17985)
    at async $.h (vscode-file://vscode-app/c:/Users/Gduddridge/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171351)
```

Any help or ideas are most welcome. 
thanks,

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by nikhgup** [comment] 2023-02-13 06:56
@geoffdudds please refer this (https://github.com/microsoft/vscode/issues/173684) issue here. It might help here.

**Comment by isidorn** [comment] 2023-02-13 09:24
Yes looks like a duplicate of that one. Thus I am closing this issue
@geoffdudds can you please comment on that issue.

**Closed by isidorn** 2023-02-13 09:24 UTC

**Comment by geoffdudds** [comment] 2023-02-13 17:25
> @geoffdudds please refer this ([microsoft/vscode#173684](https://github.com/microsoft/vscode/issues/173684)) issue here. It might help here.

Thanks, I'm surprised I didn't find this. I have commented on the other issue.
