### ISSUE TITLE
I can't update my extensions

### ISSUE THREAD

**Issue by PedroDevStudent** [microsoft/vsmarketplace#467] opened 2022-08-31 13:21 UTC
Type: <b>Bug</b>

Hello, i'm trying to update Live Server extension, but when i'm doing it, appers to manually install, the problem is, when i had done appears an error massage "{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}"

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by SaiKanth007** [comment] 2022-09-29 09:17
@PedroDevStudent We have rate limiting enabled on our endpoints and the error you are getting is because of that.

This could have been an intermittent issue as well since we block the requests if they exceed certain number from a specific IpAddress or a user. Did you try updating your extension later sometime?

**Comment by SaiKanth007** [comment] 2022-10-06 13:08
Since we didn't hear back from you, we assume that the issue is resolved and, hence closing it. Feel free to create a new ticket if you are still facing the issue.

**Closed by SaiKanth007** 2022-10-06 13:08 UTC
Labels: vscode
