### ISSUE TITLE
I can't install any extensions

### ISSUE THREAD

**Issue by IamNayana** [microsoft/vsmarketplace#894] opened 2024-04-29 16:43 UTC
Type: <b>Bug</b>

When I try to install any extention any error shows Error while installing 'Python' extension. Please check the log for more details.
Some extention which i installed earlier and due to personal eason i'm not able to use so it shows This extension is deprecated as it is no longer being maintained. Please use the built-in Settings Sync functionality instead.
Setting in vs code shows The editor could not be opened due to an unexpected error: Unexpected token 'i', "import ran"... is not valid JSON.
please help me with it.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment] 2024-05-02 17:45
Hi @IamNayana 

Thank you for reaching out to the VS Marketplace Team. We were unable to reproduce the issue. Could you please share more details about the issue so that we can take a look quickly.

VS Marketplace Team

**Comment by madhurivadaligithub** [comment] 2024-05-08 09:26
we have not heard any response, we are closing the issue. If the issue still persists, please recreate a new issue or reactivate the existing one.

Regards,
VS Marketplace Team

**Closed by madhurivadaligithub** 2024-05-08 09:26 UTC
