### ISSUE TITLE
Extension README not updated on website

### ISSUE THREAD

**Issue by symmb** [microsoft/vsmarketplace#346] opened 2022-03-09 11:28 UTC
**Describe the bug**
[Our extension's](https://marketplace.visualstudio.com/items?itemName=symflower.symflower) README is not updated on the Marketplace website after publishing an update. The extension page in VS Code shows the updated README. The extension page on the website shows the new version as the latest version but still has the old README.

At the time of writing, the version with the updated README (0.0.20998) has been published for about 15 hours and remains the latest version published.

***Update:*** New versions have been published since and the README has finally updated, so the steps below do not show the issue anymore.

**To Reproduce**
I was unable to reproduce the issue with a new extension, so I can only post the steps I took to compare the two READMEs.

1. Open VS Code
2. If installed, uninstall the `symflower.symflower` extension and restart VS Code
3. In "Extensions" open the page for `symflower.symflower`
5. Clear any browser caches and go to https://marketplace.visualstudio.com/items?itemName=symflower.symflower
6. Compare the READMEs. If the issue still persists, the README should be different in VS Code.
    - You can also just search for "Test Skeleton" which should appear in the new version but not in the old version.

**Expected behavior**
The README on the website should be the same as the README in VS Code.

**Desktop (please complete the following information):**
 - OS: openSUSE
 - Browser: Chrome, but also tried from several different locations with the Tor Browser

**Comment by jpogran** [comment] 2022-03-09 13:47
I can confirm this is also the case for https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform, which should look like https://github.com/hashicorp/vscode-terraform/blob/main/README.md

I assume this is an artifact of the recent spam mitigation?

**Comment by zimmski** [comment] 2022-03-09 19:35
> I assume this is an artifact of the recent spam mitigation?

@jpogran do you have a link on an announcement that the marketplace is doing some form of spam mitigation? Seems my Google-foo is not strong enough.

**Comment by jpogran** [comment] 2022-03-09 20:24
@zimmski https://github.com/microsoft/vsmarketplace/discussions/343

**Comment by symmb** [comment] 2022-03-10 10:49
Update: We've published new versions and the README has finally changed. I'd leave this issue open since it still seems like a bug that you have to publish another version to update the README.

I'm pretty sure it's the new version that caused it to update and not anything time-based since the Terraform extension has had its new README out for over a week now and it's still stale on the website.

**Comment by zimmski** [comment] 2022-03-10 11:51
> @zimmski #343

@jpogran thanks!

> I'm pretty sure it's the new version that caused it to update ...

@symmb will post a smaller change to the README later today. Let's see if the marketplace changes again with that pattern.

**Comment by JatinSanghvi** [comment] 2023-02-08 09:34
This one seems to be similar to https://github.com/microsoft/vsmarketplace/issues/468 since both the extensions mentioned have platform-specific packages. We have fixed the issue. I checked, the Terraform extension shows the latest committed version of Readme file on Marketplace. Please let me know if the issue still exists or whether we are good to close this issue.

**Comment by zimmski** [comment] 2023-02-08 12:46
Let's close the issue. We can always reopen if we see the problem again. We are going to have some more updates for our README anyway and then i will monitor if the updates are active right away or not.

**Comment by JatinSanghvi** [comment] 2023-02-13 03:44
Sure, feel free to reopen the issue if the problem ever resurfaces. I will close it for now.

**Closed by JatinSanghvi** 2023-02-13 03:44 UTC
Labels: bug, question
