### ISSUE TITLE
unable to search marketplace when offline 

### ISSUE THREAD

**Issue by aakarshitveersatech** [microsoft/vsmarketplace#427] opened 2022-07-07 09:24 UTC
Issue Type: <b>Bug</b>

type something in search box

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by edith-ca** [comment] 2022-07-08 03:40
no funciona css

**Comment by isidorn** [comment] 2022-08-04 10:21
Yeah, you need internet for this. Closing as by design

**Closed by isidorn** 2022-08-04 10:21 UTC
Labels: vscode
