### ISSUE TITLE
Not able to view/install any extension in the system pre-loaded VS code application

### ISSUE THREAD

**Issue by SirsaPrasanjit** [microsoft/vsmarketplace#999] opened 2024-09-05 11:04 UTC
![VS code error](https://github.com/user-attachments/assets/cf128046-81b0-4e0b-8727-9e0e3ac3c56d)
Type: <b>Feature Request</b>

Hi Team,
We are using a pre-loaded Visual studio code app in a remote desktop of Microsoft network and we are facing issue on viewing or installing any Extension on the code to proceed the work with. Kindly help to check and resolve the issue. We are not able to access the org. 

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment] 2024-09-06 18:43
Hi @SirsaPrasanjit ,

Thanks for reaching VS Marketplace Team, we are unable to reproduce the issue on our end. Could you please try again and let us know if you are still facing the same problem.

<img width="960" alt="image" src="https://github.com/user-attachments/assets/75b350fd-ac7e-40c5-9e26-01b96f2941a6">

**Comment by SirsaPrasanjit** [comment] 2024-09-09 06:54
Hi Team,

PFA screenshot, when we toggle to Extensions , we get the below error message.

***@***.***

Also, when we click on check for updates, we get the below error.
***@***.***
Is that an issue ?

Regards,
S. Prasanjit

**Comment by madhurivadaligithub** [comment] 2024-10-16 11:49
could you please submit a Fiddler trace recording to look further or share details by using MTR.

To capture MTR:
Download [WinMTR](https://sourceforge.net/projects/winmtr/files/WinMTR-v092.zip/download).

Enter marketplace.visualstudio.com as the hostname and click Start.

![Image](https://github.com/user-attachments/assets/033134e4-3407-43e2-926d-e3855668eacf)

Wait until the Sent column is >= 100.

Copy text to clipboard, share with us.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment] 2024-11-01 07:21
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

**Closed by madhurivadaligithub** 2024-11-01 07:21 UTC
Labels: needs-info
