### ISSUE TITLE
XHR

### ISSUE THREAD

**Issue by amittima1234** [microsoft/vsmarketplace#532] opened 2022-12-10 11:55 UTC
Type: <b>Bug</b>

Everytime I download an extension I'm receiving "XHR failed" error.

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

**Comment by kj0171** [comment] 2022-12-12 06:39
It seems there are network issues connecting to the Marketplace. Please open developer tools console and let us know what are the error you see while downloading extensions. You can open developer tools console using following command F1 > Toggle Developer Tools

**Comment by JatinSanghvi** [comment] 2023-02-04 05:40
This is same as #533 which was created on the same day. This turned out to be a temporary issue. The users who original reported it are no longer seeing it. I will close this one. @amittima1234, if you are still facing this issue, please follow the steps as I mentioned in https://github.com/microsoft/vsmarketplace/issues/540#issuecomment-1411490797 and we will reconsider. It would also be helpful if you can add a comment below stating whether the issue is fixed or still persists.

**Closed by JatinSanghvi** 2023-02-04 05:40 UTC
