### ISSUE TITLE
The README.md in the marketplace is not updating for Swimm.swimm

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vsmarketplace#431] opened 2022-07-13 11:10 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.1
- OS Version: macOS 12.4

Our new `README.md` for our extension (Swimm.swimm) is not showing/updating in the marketplace. One suspect here is that the extension used to be universal and download binaries from the net and now it is platform specific. But there might be any other issue causing this. If I should direct this issue towards somewhere else, please let me know.

Extension: https://marketplace.visualstudio.com/items?itemName=Swimm.swimm

**Comment by prashantvc** [comment] 2022-07-13 14:59
@segevfiner aw no! We are looking into it on priority. I will keep you posted on the progress

**Comment by SaiKanth007** [comment] 2022-07-13 15:11
@segevfiner We are aware of this issue, https://github.com/microsoft/vsmarketplace/issues/415 has more details.
We will soon be rolling out a fix for this.

Regarding the license & changelog.md, I am able to view the content and don't see 404 error. 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/17098988/178768308-adbd1d03-02e6-44b3-b4c5-cd00276d4b86.png">

<img width="937" alt="image" src="https://user-images.githubusercontent.com/17098988/178768422-15870356-fb79-45dc-995a-d3eb0e493995.png">

**Comment by segevfiner** [comment] 2022-12-05 13:31
We have now released a new version with a new `README.md` and it hasn't updated yet again. 😢

**Comment by JatinSanghvi** [comment] 2023-01-18 12:16
The fix for the issue is committed and should become available with a future release. I should update this issue in 2-3 weeks once we have the fix deployed.

**Comment by JatinSanghvi** [comment] 2023-02-04 05:30
We have confirmation from #468 that the issue is fixed. I will close this one.

**Closed by JatinSanghvi** 2023-02-04 05:30 UTC
