### ISSUE TITLE
Copy button is broken

### ISSUE THREAD

**Issue by johnnygerard** [microsoft/vsmarketplace#600] opened 2023-02-28 15:37 UTC
**Describe the bug**
The `Copy` button does not work.

**To Reproduce**
1. Click on the `Copy` button.

**Expected behavior**
The command gets copied into the clipboard.

**Actual behavior**
Nothing happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/57420910/221901368-a299e304-7022-4dd6-ae6a-f4d81fd9cd0e.png)

**Desktop environment**
 - Ubuntu 22.04.2 LTS
 - Chrome Version 110.0.5481.177 (Official Build) (64-bit)

**Comment by kj0171** [comment] 2023-03-01 08:09
Thank you for reporting this.
We are looking into this.

**Comment by johnnygerard** [comment] 2023-05-24 13:05
The `Copy` button works with the URL query parameter `ssr=false`.
- [GitHub Pull Requests and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) (original)
- [GitHub Pull Requests and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github&ssr=true) (`ssr=true`)
- [GitHub Pull Requests and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github&ssr=false) (`ssr=false`)

**Desktop environment**
Ubuntu 23.04 Lunar
Chrome 113.0.5672.126 (Official Build) (64-bit)

**Comment by 1j01** [comment] 2023-09-07 20:23
This is a duplicate of #366 and #51.

What is the `ssr` parameter?

**Closed** 2023-10-10 13:23 UTC
Labels: bug
