### ISSUE TITLE
xhr failed

### ISSUE THREAD

**Issue by yoni1998-26** [microsoft/vsmarketplace#552] opened 2023-01-09 20:03 UTC
Type: <b>Performance Issue</b>

can't download extensition

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by JatinSanghvi** [comment] 2023-01-10 08:06
Hi @yoni1998-26, can you let us know the HTTP URLs of the requests that are failing, and the country from where you are trying to download the extension? We are trying to investigate a similar issue where it's specific to a particular CDN that is serving the requests to selected regions, so based on your information, we can figure out if it's the same or a different issue.

**Comment by JatinSanghvi** [comment] 2023-01-10 08:15
Hi @yoni1998-26, I was talking about issue #533. It seems similar to the one that you reported.  If possible, can you export the requests to a HAR file and get us the client-info headers and email them to us? You can find the steps in https://github.com/microsoft/vsmarketplace/issues/533#issuecomment-1373857199.

**Comment by JatinSanghvi** [comment] 2023-01-16 04:37
Hi @yoni1998-26, please let us know if the issue is still reproducible. We will close this issue if we do not get a response.

**Comment by JatinSanghvi** [comment] 2023-01-17 04:35
Hi, we will go ahead and close the issue. Feel free to reopen it if you still get the error. Thanks.

**Closed** 2023-01-17 04:42 UTC
