### ISSUE TITLE
VSIXPackage for redhat.java 1.2.0 is actually 1.1.0

### ISSUE THREAD

**Issue by justinkb** [microsoft/vsmarketplace#288] opened 2022-01-02 20:54 UTC
**Describe the bug**
The VSIXPackage for redhat.java 1.2.0, found on https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/java/1.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage - is actually 1.1.0.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by prashantvc** [comment] 2022-01-03 06:54
Could you file the issue with Java extension team please? https://github.com/redhat-developer/vscode-java

**Comment by testforstephen** [comment] 2022-01-04 02:37
Starting with 1.2.0, redhat.java only published platform-specific versions, and the Marketplace page correctly displays these versions. Also, we were told not to publish a generic version if a platform-specific version was released.

![image](https://user-images.githubusercontent.com/14052197/148001050-3a8b18b9-368c-4a88-a0c7-01459f31c5d7.png)

It looks like using the API to request 1.2.0 without specifying the target platform, it just returns the latest available generic version (e.g. 1.1.0). This seems a bug in the marketplace API. 

@prashantvc Could you pls reopen the issue and take a look on your side? Also could you pls clarify what action, if any, should be taken on the extension publisher side?

// cc: @isidorn

**Comment by justinkb** [comment] 2022-01-04 06:42
If I replace "1.2.0" in the URL with "latest", it does grab the vsix I want. Does that track with your statements above?

**Comment by testforstephen** [comment] 2022-01-04 07:06
I'm curious why you need to use API to grab the vsix, would you mind sharing your use case? @justinkb

**Comment by justinkb** [comment] 2022-01-04 07:29
I ran into this while using NixOS. Because of its design, you need to
declare the extensions you want to use.

It then grabs the file, per

https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vscode-extensions/vscode-utils.nix

which references

https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vscode-extensions/mktplcExtRefToFetchArgs.nix

and that's ultimately where the URL it's grabbing is defined.

I've switched to the vscode-fhs (sets up a virtual FHS environment and
chroots into it) since, so this is no longer an issue for me. I just
figured I'd report the odd thing I noticed.

**Comment by testforstephen** [comment] 2022-01-04 08:00
@justinkb thanks for sharing the use case. I'll wait for the VS Code Marketplace team to clarify the issue first, then provide fixes if necessary.

**Comment by isidorn** [comment] 2022-01-04 17:35
Let me reopen and assign to @prashantvc so he can comment.

**Comment by SaiKanth007** [comment] 2022-01-06 04:39
@justinkb We expect the API to be called with appropriate targetPlatform that the version supports. The VSCode client takes care of this.

Falling back to the latest generic version is intentional, this was done to support older VSCode clients which doesn't know anything about targetPlatform and doesn't support platform specific extensions.

Also can you add some details about the scenario where you are using the API directly ?

**Comment by justinkb** [comment] 2022-01-06 06:33
I've detailed how I ran into this in my previous comment in this thread.

**Comment by prashantvc** [comment] 2022-02-15 06:29
Closing this issue, it works as designed (https://github.com/microsoft/vsmarketplace/issues/288#issuecomment-1006279371)

**Closed by prashantvc** 2022-02-15 06:29 UTC
Labels: bug
