### ISSUE TITLE
Error while installing 'x' extension. Please check the log for more details.

### ISSUE THREAD

**Issue by Tonio92345** [microsoft/vsmarketplace#821] opened 2023-12-04 05:58 UTC
Type: <b>Feature Request</b>

I don't know why, if I try to install an extension form the VSCode marketplace, this error occurs "Error while installing 'x' extension. Please check the log for more details". I tried googling to find a solution, but nothing. How can I do? I don't want to download extensions manually.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment] 2023-12-08 14:11
Hi @Tonio92345 

Thanks for reaching VS Marketplace Support Team, could you please share the error screenshot along with the reproduction steps? This additional information will greatly assist us in investigating and resolving the issue more effectively.

Thanks,
-VS Marketplace Team

**Comment by madhurivadaligithub** [comment] 2024-01-19 08:10
Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.

**Closed by madhurivadaligithub** 2024-01-19 08:10 UTC
Labels: needs-info
