### ISSUE TITLE
prefixes non-links in the Extension Readme

### ISSUE THREAD

**Issue by gauravmak** [microsoft/vsmarketplace#27] opened 2020-05-09 07:20 UTC
Issue Type: <b>Bug</b>

VS code and Marketplace automatically prefixes the links in the Readme of the package as per the homepage URL set in the `package.json` file.

In [my case](https://marketplace.visualstudio.com/items?itemName=freshbitsweb.laravel-traveller), it is prefixing a non-link as well. At multiple places, I am displaying `regex` statements to the users but the homepage URL is prefixed inside a regex. I am already wrapping regex with backticks so they are not actually considered links. 

My regex for this line is: `^\s*return view\(['"](.*?)['"].*\).*$`
![Check attached screenshot for reference](https://user-images.githubusercontent.com/11887260/81467008-683b0400-91f3-11ea-8270-9261909630f7.png)

I have read the [related documentation page](https://code.visualstudio.com/api/references/extension-manifest#marketplace-presentation-tips) already. 

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.15.0-99-generic

**Comment by isidorn** [comment] 2021-08-20 09:52
Closing as outdated

**Closed by isidorn** 2021-08-20 09:52 UTC

**Comment by gauravmak** [comment] 2021-08-20 13:30
Is the issue fixed @isidorn ?

**Comment by isidorn** [comment] 2021-08-20 13:34
Well it is up to you to please try the steps from https://github.com/microsoft/vsmarketplace/issues/27#issuecomment-703603522 and let us know if the issue is still appearing. If yes we can reopen the issue. Thanks

**Comment by gauravmak** [comment] 2021-08-20 13:53
Just tried and it's fixed :)

Thanks.
