### ISSUE TITLE
couldnot install extensions

### ISSUE THREAD

**Issue by newbieamir** [microsoft/vsmarketplace#217] opened 2021-10-21 16:37 UTC
Issue Type: <b>Bug</b>

couldn't install any extensions or update it at all

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Neelima10735584** [comment] 2024-10-29 11:40
Hi,

Thanks for reaching VS Marketplace Team, If the error is still persisting, please share a screenshots or error messages that you encountered or reproduce steps to investigate further.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment] 2024-11-01 07:21
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

**Closed by madhurivadaligithub** 2024-11-01 07:21 UTC
Labels: needs-info
