### ISSUE TITLE
Extension not found when filtering for the supported Visual Studio version

### ISSUE THREAD

**Issue by realvizu** [microsoft/vsmarketplace#527] opened 2022-12-06 13:28 UTC
I have two Visual Studio extensions on Visual Studio marketplace, one supports VS 2019 and the other supports VS 2022.
I can find them by searching for the "diagram" keyword, but only if I set the Version filter dropdown to "Any". If I set the Version filter to the concrete VS version that they support (VS 2019 or VS 2022) then they cannot be found.

**To Reproduce**
1. Go to https://marketplace.visualstudio.com/vs
2. In the search box type "diagram" and click the search button
3. The first result (when sorted by relevance) is one of my extensions: "Codartis Diagram Tool for C# (VS2019)"
4. Now choose "Visual Studio 2019" in the version filter dropdown.
5. My extension is not in the result list any more. (Although it supports Visual Studio 2019, as confirmed by its page: https://marketplace.visualstudio.com/items?itemName=FerencVizkeleti.QuickDiagramToolforC )

**Expected behavior**
When I search for the "diagram" keyword and I set the Version filter to "Visual Studio 2019" then I expect my extension called "Codartis Diagram Tool for C# (VS2019)" to be in the result list.

**Screenshots**
![image](https://user-images.githubusercontent.com/7570679/205921766-60d3cc45-d274-4679-8b4b-db80e4d88a2f.png)
![image](https://user-images.githubusercontent.com/7570679/205921921-9315b97a-c95c-4776-9968-a594a1766c26.png)
![image](https://user-images.githubusercontent.com/7570679/205922047-27c1b050-0176-4693-a366-38ffd60f95fa.png)

**Additional context**
* The same problem happens with my other extension that supports VS 2022. Its name is: "Codartis Diagram Tool for C# (VS2022)". When I search for the "diagram" keyword and "Any" version then it's in the result list. When I set the Version filter to "Visual Studio 2022" then my extension is not in the result list any more. Although it supports VS 2022 as confirmed by its page: https://marketplace.visualstudio.com/items?itemName=FerencVizkeleti.diagramtool-vs2022
* The problem does not occur when I search for my extensions from Visual Studio's "Manage Extensions" dialog. If I search there for the "diagram" keyword then my extension is in the result list, as expected, both in VS 2019 and in VS 2022.

**Comment by kj0171** [comment] 2022-12-12 12:00
Thanks for bringing this to our notice. We are looking into this.

**Comment by realvizu** [comment] 2023-03-04 07:34
@kj0171 @prashantvc Any news on this? It's quite a problem for me because people can't find my extensions.

**Comment by AnthonyByansi** [comment] 2023-03-04 07:45
I've just given it a try and neither can I see the "Codartis Diagram Tool for C# (VS2019)" I thought it could be a Cache issue. This needs to be addressed @realvizu

**Comment by realvizu** [comment] 2023-04-02 18:48
@SaiKanth007 Hi! Any news on this issue? Thanks!

**Comment by realvizu** [comment] 2023-05-03 11:45
Hi @xavierdecoster ! I'd like to ask if there's any progress on this ticket? thanks!

**Comment by ErikEJ** [comment] 2023-05-03 11:47
What does your vsix manifest look like?

**Comment by realvizu** [comment] 2023-05-03 11:51
```xml
<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011" xmlns:d="http://schemas.microsoft.com/developer/vsx-schema-design/2011">
    <Metadata>
        <Identity Id="09b0e9a9-7a0a-43c1-a55b-652f69d0232d" Version="1.3.0" Language="en-US" Publisher="Codartis" />
        <DisplayName>Codartis Diagram Tool for C# (VS2022)</DisplayName>
        <Description xml:space="preserve">Code visualization tool for C# to quickly explore, navigate and document source code structure and relationships.</Description>
        <MoreInfo>https://codartis.com</MoreInfo>
        <License>LICENSE.txt</License>
        <GettingStartedGuide>https://github.com/Codartis/DiagramTool/blob/main/help/Help.md#getting-started</GettingStartedGuide>
        <Icon>Resources\CodartisDiagramTool_128.ico</Icon>
        <PreviewImage>Resources\CodartisDiagramTool_256.png</PreviewImage>
        <Tags>code;visualize;codartis;quick;diagram;uml;c#;csharp;tool;inheritance;interface;codemap</Tags>
    </Metadata>
    <Installation>
        <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.2, 18.0)">
            <ProductArchitecture>amd64</ProductArchitecture>
        </InstallationTarget>
        <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[17.2, 18.0)">
            <ProductArchitecture>amd64</ProductArchitecture>
        </InstallationTarget>
        <InstallationTarget Id="Microsoft.VisualStudio.Enterprise" Version="[17.2, 18.0)">
            <ProductArchitecture>amd64</ProductArchitecture>
        </InstallationTarget>
    </Installation>
    <Dependencies>
        <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" d:Source="Manual" Version="[4.7.2,)" />
    </Dependencies>
    <Prerequisites>
        <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[17.0,)" DisplayName="Visual Studio core editor" />
        <Prerequisite Id="Microsoft.VisualStudio.Component.Roslyn.LanguageServices" Version="[17.0,)" DisplayName="C# and Visual Basic" />
    </Prerequisites>
    <Assets>
        <Asset Type="Microsoft.VisualStudio.VsPackage" d:Source="Project" d:ProjectName="%CurrentProject%" Path="|%CurrentProject%;PkgdefProjectOutputGroup|" />
    </Assets>
</PackageManifest>
```

**Comment by realvizu** [comment] 2023-05-03 12:00
I've tried to compare my vsixmanifest with some other ones that do appear correctly in the VS version filtered list, but I could not figure out what difference can cause it.

**Comment by ErikEJ** [comment] 2023-05-03 12:43
Maybe the extra space in the version range?

**Comment by realvizu** [comment] 2023-05-03 13:04
My other package (which also does not show up when filtered for VS version) does not have the extra space, but still does not work.

```xml
<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011" xmlns:d="http://schemas.microsoft.com/developer/vsx-schema-design/2011">
    <Metadata>
        <Identity Id="7481ead5-87e4-4ac0-86d1-317e7adab60c" Version="1.3.0" Language="en-US" Publisher="Codartis" />
        <DisplayName>Codartis Diagram Tool for C# (VS2019)</DisplayName>
        <Description xml:space="preserve">Code visualization tool for C# to quickly explore, navigate and document source code structure and relationships.</Description>
        <MoreInfo>https://codartis.com</MoreInfo>
        <License>LICENSE.txt</License>
        <GettingStartedGuide>https://github.com/Codartis/DiagramTool/blob/main/help/Help.md#getting-started</GettingStartedGuide>
        <Icon>Resources\CodartisDiagramTool_128.ico</Icon>
        <PreviewImage>Resources\CodartisDiagramTool_256.png</PreviewImage>
        <Tags>code;visualize;codartis;quick;diagram;uml;c#;csharp;tool;inheritance;interface;codemap</Tags>
    </Metadata>
    <Installation>
        <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[16.11,17.0)" />
        <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[16.11,17.0)"  />
        <InstallationTarget Id="Microsoft.VisualStudio.Enterprise" Version="[16.11,17.0)" />
    </Installation>
    <Dependencies>
        <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" d:Source="Manual" Version="[4.7.2,)" />
    </Dependencies>
    <Assets>
        <Asset Type="Microsoft.VisualStudio.VsPackage" d:Source="Project" d:ProjectName="%CurrentProject%" Path="|%CurrentProject%;PkgdefProjectOutputGroup|" />
    </Assets>
    <Prerequisites>
        <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[16.0,)" DisplayName="Visual Studio core editor" />
        <Prerequisite Id="Microsoft.VisualStudio.Component.Roslyn.LanguageServices" Version="[16.0,)" DisplayName="C# and Visual Basic" />
    </Prerequisites>
</PackageManifest>
```

Also, I've found this package, which works as expected (shows up in the VS version filtered list), and also has the space in the version range.
Package: https://marketplace.visualstudio.com/items?itemName=AndreHass.YouML1
Vsixmanifest: https://github.com/ahass/YouML/blob/master/YouML/source.extension.vsixmanifest

**Comment by realvizu** [comment] 2023-05-03 13:09
Another potential cause: in my vsixmanifests the "from" part of the version range is not "16.0" or "17.0", but "16.11" and "17.2". If the VS version filter matches for exact "16.0" or "17.0", that would be an explanation for the problem.

However, I can't change the version ranges in may files to "16.0" and "17.0", because I depend on certain Roslyn versions that were introduced with the specified VS versions.

**Comment by xavierdecoster** [comment] 2024-10-04 13:57
Closing this issue as I am no longer able to reproduce. Let us know if you continue to run into similar issues.

**Closed by xavierdecoster** 2024-10-04 13:57 UTC
Labels: bug

**Comment by ErikEJ** [comment] 2024-10-04 16:49
@xavierdecoster Did you test with a package that constrains support to 17.0 or newer (and not 17.0) ??

I only support 17.5 but have to frequently tell users to upgrade from older versions because the extension crashes - not a good UX
