### ISSUE TITLE
can't  create publisher

### ISSUE THREAD

**Issue by 330595524** [microsoft/vsmarketplace#57] opened 2021-04-12 12:44 UTC
![image](https://user-images.githubusercontent.com/17978272/114396148-cb85a100-9bcf-11eb-80f4-fad1a81ae1dc.png)

i can link  https://marketplace.visualstudio.com/manage/createpublisher  but not create

**Comment by prashantvc** [comment] 2021-04-16 07:40
Duplicate of #31

**Closed by prashantvc** 2021-04-16 07:40 UTC
Labels: bug
