### ISSUE TITLE
Markdown renderer doesn't handle <picture> and <source> elements when SSR is false

### ISSUE THREAD

**Issue by printfn** [microsoft/vsmarketplace#1065] opened 2024-11-12 00:50 UTC
Type: <b>Bug</b>

Viewing this extension in the web browser works fine:
https://marketplace.visualstudio.com/items?itemName=printfn.jpeg-xl

But when you switch between the tabs ("Overview", "Q & A", "Rating & Review" etc.) then you go to https://marketplace.visualstudio.com/items?itemName=printfn.jpeg-xl&ssr=false (note the `ssr=false` parameter), which renders the image incorrectly. It looks like `<picture>` and `<source>` elements aren't enabled in the markdown renderer when ssr is false.

![Image](https://github.com/user-attachments/assets/fe285426-6d15-40de-adaf-33eaf9842da4)

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

**Comment by Neelima10735584** [comment] 2024-11-14 12:29
Closing as duplicate of https://github.com/microsoft/vsmarketplace/issues/1049

**Closed by Neelima10735584** 2024-11-14 12:29 UTC
