### ISSUE TITLE
Copilot rate-limited

### ISSUE THREAD

**Issue by jandrestrauss** [microsoft/vsmarketplace#1097] opened 2024-12-22 23:35 UTC
Type: <b>Bug</b>

rate-limited permantly on pro version

VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.26100
Modes:

**Comment by Neelima10735584** [comment] 2024-12-23 08:17
Hi,

Thanks for reaching VS Marketplace Support Team, could you please share detailed steps to reproduce the issue, screenshot or error message to investigate further.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment] 2024-12-26 01:03
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team

**Closed by Neelima10735584** 2024-12-26 01:03 UTC
Labels: needs-info, Customer Support
