### ISSUE TITLE
1.74.0 broke XHR connection to extension platform

### ISSUE THREAD

**Issue by StanLaurent** [microsoft/vsmarketplace#533] opened 2022-12-10 12:52 UTC
Does this issue occur when all extensions are disabled?: No, the issue is related to extensions

- VS Code Version: 1.74.0
- OS Version: Windows 10 (Build 19045.2251)

Steps to Reproduce:

1. Update to 1.74.0
2. The pages of not installed extensions won't load. Installing or updating extensions won't work.
3. When opening VSCode, the console logs the following error:
`XHR failed: Error: XHR failed at C.onerror`
`(vscode-file://vscode-app/c:/Users/myWindowsUserame/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:16:55537)`

Edit: it happened after I updated, but reinstalling an older version does not fix the issue.

Edit 2: switching to the mobile network (Swisscom) solves the issue, it must have to do with VS Code's connection to the wifi network but no proxy or router settings were changed.

Edit 3: happening only on 1 device so it's not just network related.

![image](https://user-images.githubusercontent.com/109153151/206856676-f83e911b-1d69-4659-8d17-97e1e2eea8c1.png)

![image](https://user-images.githubusercontent.com/109153151/206856870-da9dea25-e257-49a8-97fc-78dc692619c1.png)

**Comment by prashantvc** [comment] 2022-12-12 04:55
Working with engineering on this!

**Comment by igagis** [comment] 2023-01-05 07:54
I have the same issue. I'm behind corporate proxy, for which I have `http_proxy`, `https_proxy` env vars set.

I can search for extensions in vscode, but I cannot install them, or even see any extension's manifest page. Getting this error:
```
2023-01-05 09:52:12.302 [error] RequestService#request (browser) - error https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cpptools/1.13.9/assetbyname/Microsoft.VisualStudio.Code.Manifest?targetPlatform=linux-x64 {}
2023-01-05 09:52:12.303 [error] Error: XHR failed
    at b.onerror (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1428)
```

I'm running Debian 11 in Virtualbox on windows host.

**Comment by JatinSanghvi** [comment] 2023-01-06 16:19
@StanLaurent, @suntsu42, @mgwrd - We have opened a support ticket with our CDN provider. They have asked us for following information:

1. HTTP requests exported in HAR format. To do this,
    a. Ensure that the extension page is still not loading.
    b. In Visual Studio Code, open Developer Tools (Ctrl+Shift+I).
    c. Switch to the Network tab and enable the 'Disable Cache' option.
    d. Open the extension page again.
    e. Right click on any request and select Copy > Copy all as HAR.
    f. Save the copied text in a file and email it to us (VSMarketplace [at]microsoft .com).
    
2. Headers copied after opening page: http://wpc.2dcc.edgecastcdn.net/002DCC/n2/.
    Go to the page, expand 'Client Info', copy all rows underneath, save it in a file and email it to us.

**Comment by JatinSanghvi** [comment] 2023-01-16 04:48
Hi, our CDN vendor is pushing towards closing the ticket that we had opened. It seems that the issue has stopped happening as there have been no new activity on this issue for a while. If there are no new responses here or via emails, we will need to close this issue. Even after it gets closed, feel free to add comments if the error becomes reproducible and we will reopen it.

**Comment by mgwrd** [comment] 2023-01-16 06:53
It stopped happening shortly after it started.

**Comment by JatinSanghvi** [comment] 2023-01-17 04:33
Thanks @mgwrd. I will close the issue. As I mentioned earlier, feel free to add comment or reopen the issue in case it surfaces again.

**Comment by igagis** [comment] 2023-01-17 13:18
I still see the issue

**Comment by amit-kulkarni-in** [comment] 2023-01-17 13:20
@igagis  Can you please share the below information .
HTTP requests exported in HAR format. To do this,
a. Ensure that the extension page is still not loading.
b. In Visual Studio Code, open Developer Tools (Ctrl+Shift+I).
c. Switch to the Network tab and enable the 'Disable Cache' option.
d. Open the extension page again.
e. Right click on any request and select Copy > Copy all as HAR.
f. Save the copied text in a file and email it to us (VSMarketplace [at]microsoft .com).

Headers copied after opening page: http://wpc.2dcc.edgecastcdn.net/002DCC/n2/.
Go to the page, expand 'Client Info', copy all rows underneath, save it in a file and email it to us.

**Comment by igagis** [comment] 2023-01-17 14:19
done

**Comment by MoheyEl-DinBadr** [comment] 2023-02-09 00:45
same issue here: 
![Screenshot from 2023-02-09 02-44-29](https://user-images.githubusercontent.com/56153924/217685418-7b424682-8db3-4638-9344-fabaa7e202c1.png)

**Comment by JatinSanghvi** [comment] 2023-02-13 03:58
Hi @MoheyEl-DinBadr, can you also send the network traffic exported as a HAR file, as I requested in https://github.com/microsoft/vsmarketplace/issues/533#issuecomment-1373857199?

**Comment by MoheyEl-DinBadr** [comment] 2023-02-13 22:02
> Hi @MoheyEl-DinBadr, can you also send the network traffic exported as a HAR file, as I requested in [#533 (comment)](https://github.com/microsoft/vsmarketplace/issues/533#issuecomment-1373857199)?

Actually It surprisingly it works now after last update

**Comment by JatinSanghvi** [comment] 2023-02-14 04:20
Closing the issue since it was intermittent, and we weren't able to collect the details while it existed.

Since this GitHub issue has been used to investigate issues from multiple users (having same or different root causes), and since none of the user is currently seeing this issue, they may not want to be notified for every activity. Hence, requesting anyone who encounters the XHR connection error to **open a NEW GitHub issue**, instead of commenting on this one.

**Closed by JatinSanghvi** 2023-02-14 04:20 UTC
