### ISSUE TITLE
I can install any exensions

### ISSUE THREAD

**Issue by EricTulowetzke** [microsoft/vsmarketplace#536] opened 2022-12-14 03:41 UTC
Type: <b>Bug</b>

1. using arch linux 
2. yay -S visual-studio-code-insiders-bin
3. start vscode and try to install any exension and you get this 

2022-12-13 21:34:46.161 [info] Electron sandbox mode is enabled!
2022-12-13 21:34:49.966 [info] [perf] Render performance baseline is 38ms
2022-12-13 21:35:05.163 [error] Error: UnknownError,UnknownError
    at vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88601
    at Array.reduce (<anonymous>)
    at u (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88587)
    at _.D (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:79941)
    at async _.z (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:77475)
    at async _.installFromGallery (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:73918)
2022-12-13 21:35:05.189 [error] UnknownError,UnknownError: Error: UnknownError,UnknownError
    at vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88601
    at Array.reduce (<anonymous>)
    at u (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88587)
    at _.D (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:79941)
    at async _.z (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:77475)
    at async _.installFromGallery (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:73918)
2022-12-13 21:40:24.098 [error] spawn truecolor ENOENT: Error: spawn truecolor ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

VS Code version: Code - Insiders 1.75.0-insider (d7b1e2a1c892511a125e4ceb9758ec8ddf907775, 2022-12-12T12:40:10.825Z)
OS version: Linux x64 6.0.12-zen1-1-zen
Modes:
Sandboxed: Yes

**Comment by madhurivadaligithub** [comment] 2022-12-14 07:03
@EricTulowetzke If the issue is related to VS Code, please file in https://github.com/microsoft/vscode/issues

**Comment by isidorn** [comment] 2022-12-14 08:48
Sounds like a duplicate of https://github.com/microsoft/vscode/issues/164726

**Closed by isidorn** 2022-12-14 08:48 UTC
