### ISSUE TITLE
Extensions Dosen't Work

### ISSUE THREAD

**Issue by xjoe93** [microsoft/vsmarketplace#589] opened 2023-02-18 20:19 UTC
Type: <b>Bug</b>

when i wan to install any extension it dosen't install 

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment] 2023-02-23 06:41
duplicate of this active one https://github.com/microsoft/vsmarketplace/issues/591 hence closed.

**Closed by madhurivadaligithub** 2023-02-23 06:41 UTC
