### ISSUE TITLE
Unhandled 500 `ReCaptcha token is invalid` when editing review response

### ISSUE THREAD

**Issue by radeksimko** [microsoft/vsmarketplace#137] opened 2021-08-04 07:26 UTC
**Describe the bug**

Unable to edit review response to a review in the Marketplace.

**To Reproduce**

How to reproduce (as extension publisher)

This happened after I managed to edit a few reviews successfully after initially completing the ReCaptcha.

1. Go to “Ratings & Reviews” page
1. Scroll down to a review with existing response
1. Click “Edit”
1. Make any changes in the response
1. Click “Submit”

The result is a forever spinning animation:

![B71c4da8424ab46be9e3f29443e0baf2a637634897481880504_Screenshot_2021-08-02_at_09 28 41](https://user-images.githubusercontent.com/287584/128138927-8239ee33-3831-4f80-b56c-404ef21623c2.png)

I am not presented with any more ReCaptcha.

I can see that a request was made to the backend which resulted in HTTP 500 error, if I open the DevTools in Chrome:

Request URL: `https://marketplace.visualstudio.com/_apis/gallery/publishers/.../extensions/.../reviews/…`
Request Method: PATCH

Status Code: `500`
Response:

```json
{
  "$id": "1",
  "innerException": null,
  "message": "ReCaptcha token is invalid.",
  "typeName": "Microsoft.VisualStudio.Services.Gallery.WebApi.InvalidReCaptchaTokenException, Microsoft.VisualStudio.Services.Gallery.WebApi",
  "typeKey": "InvalidReCaptchaTokenException",
  "errorCode": 0,
  "eventId": 3000
}
```

which was unhandled by the frontend code it looks like:

```
Error handling rest error: TypeError: Cannot read property 'handleError' of undefined
    at Object.<anonymous> (https://cdn.vsassets.io/bundles/vss-bundle-common-vAxTfiXyVVXw6yenpoCw6U9J-vYliIFKC5gLmxAw0Ve0=:584:2195)
    at Object.<anonymous> (https://cdn.vsassets.io/bundles/vss-bundle-basejs-v9GpWWBnsWqhM23ijhK2HfAqLowTXGUqZLDRsBCZbkfY=:3:28469)
    at i (https://cdn.vsassets.io/bundles/vss-bundle-basejs-v9GpWWBnsWqhM23ijhK2HfAqLowTXGUqZLDRsBCZbkfY=:3:27151)
    at Object.fireWith [as rejectWith] (https://cdn.vsassets.io/bundles/vss-bundle-basejs-v9GpWWBnsWqhM23ijhK2HfAqLowTXGUqZLDRsBCZbkfY=:3:27914)
    at z (https://cdn.vsassets.io/bundles/vss-bundle-basejs-v9GpWWBnsWqhM23ijhK2HfAqLowTXGUqZLDRsBCZbkfY=:5:12084)
    at XMLHttpRequest.<anonymous> (https://cdn.vsassets.io/bundles/vss-bundle-basejs-v9GpWWBnsWqhM23ijhK2HfAqLowTXGUqZLDRsBCZbkfY=:5:15619)
```

**Expected behavior**

Editing of review response to succeed.

**Desktop:**
 - OS: macOS 10.15.7
 - Browser: Google Chrome
 - Version: 92.0.4515.107

**Comment by radeksimko** [comment] 2021-08-10 10:26
@prashantvc This bug has been present for the last two weeks and we are still unable to edit any of our review responses.

Would you mind looking into this or advice how to proceed? 🙏🏻

**Comment by prashantvc** [comment] 2021-08-10 12:00
@SaiKanth007 can you take a look at this please?

**Comment by SaiKanth007** [comment] 2021-08-11 07:41
@radeksimko we are aware of this and are currently looking into it. In the mean while as a work around, you can respond to the review from an other user who has contributor/owner access to the publisher.

The challenge with this issue is, we are not able to reproduce this on our end and also this is happening only to few users at random.

**Comment by radeksimko** [comment] 2021-08-11 09:42
@SaiKanth007 Understood, let me know if I can help in any way - I'd be happy to jump on a video call and share screen or collect any more details to help you debug this. Feel free to reach me on `radek<at>hashicorp.com`

**Comment by SaiKanth007** [comment] 2021-08-13 09:10
@radeksimko Currently we are not allowed to take contributions/help from outside. Appreciate your offer for help.

**Comment by henryju** [comment] 2021-09-09 15:31
I'm not sure if this is the same issue, but I'm unable to upload a new version of our extension. I receive the same error "ReCaptcha token is invalid" after upload is completed.

**Comment by amit-kulkarni-in** [comment] 2022-12-23 10:36
We have disabled re-captcha on the ratings and review page. Hence closing this issue.

**Closed by amit-kulkarni-in** 2022-12-23 10:36 UTC
Labels: bug
