### ISSUE TITLE
copy is invalid

### ISSUE THREAD

**Issue by joinAnd** [microsoft/vsmarketplace#400] opened 2022-05-19 11:06 UTC
Issue Type: <b>Bug</b>

In the information page of the extension,If the text is selected, the copy in the right mouse button menu is invalid

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by isidorn** [comment] 2022-05-30 15:39
I can not reproduce this. Can you provide a bit more details?
For example information page in the browser on the Marketplace website, or in VS Code itselft?
Could you provide a short gif demonstrating this? Thanks

**Comment by isidorn** [comment] 2022-06-28 12:25
Since no more details have been provided I will go ahead and close this issue. Once you provide more details we can reopen.

**Closed by isidorn** 2022-06-28 12:25 UTC
