### ISSUE TITLE
Marketplace Extension Manifest - SemVer not actually supported

### ISSUE THREAD

**Issue by glenn2223** [microsoft/vsmarketplace#46] opened 2021-04-03 15:37 UTC
Initially reported [here](https://github.com/microsoft/vscode/issues/120389)

---

Site ref: https://code.visualstudio.com/api/references/extension-manifest#fields
Github doc: https://github.com/microsoft/vscode-docs/blob/a641ec03073b116b12b9f5fcee95c024a79c6899/api/references/extension-manifest.md

It states under `version` that it's SemVer compatible. However, if I suffix a version with `-rc.1` - which SemVer document, and have even [used themselves](https://semver.org/spec/v2.0.0-rc.2.html) (figure 1) - I get an error (figure 2)

**Table row copied from the page**
Name | Required | Type | Details
-- | -- | -- | --
version | Y | string | SemVer compatible version.

![image](https://user-images.githubusercontent.com/33450392/113360837-7bdae600-9342-11eb-962d-33fb95c47907.png)
(figure 1 - SemVer's own version of release candidate)

![image](https://user-images.githubusercontent.com/33450392/113360899-9d3bd200-9342-11eb-89d4-55254745acd2.png)
(figure 2 - Error displayed saying that only #.#.#.# is allowed)

---

Side note: `vsce package` allows me to package with SemVer versioning but not the recommended (from figure 2) 4 numbers separated with dots

So `#.#.#-A.#` packages up but `#.#.#.#` doesn't (where `#` is any number length and `A` is any alpha length)

**Comment by gjsjohnmurray** [comment] 2021-04-18 03:55
duplicate of #50

**Comment by isidorn** [comment] 2021-12-10 09:16
Let close as duplicate

**Closed by isidorn** 2021-12-10 09:16 UTC
Labels: bug, enhancement
